org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=lenguaperdida
mod_name=La Lengua Perdida
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.mopiux.lenguaperdida
mod_authors=mopiux, Claude (Anthropic)
mod_description=Cada mundo genera una civilización antigua con su propio idioma y glifos. Explorá ruinas, reuní piedras Rosetta y descifrá inscripciones que te llevan a bóvedas selladas.
